### ISSUE TITLE
Feature request: Live update stubs

### ISSUE THREAD

**Issue by jamesarosen** [pact-foundation/pact-stub-server#52]
### Problem

If I run the server as follows:
```yaml
pact-stub:
  command:
    - "-p3001"
    - "-dpacts"
  container_name: my-pact-stub
  image: pactfoundation/pact-stub-server
  ports:
    - "3001:3001"
  tty: true
  volumes:
    - "./test/pacts/:/app/pacts:ro"
```
and then change one of the files in `test/pacts/` (either manually or by running my unit tests), the change is not reflected in subsequent requests to the server without restarting it.

### Why this matters

Following the [Writing Consumer Tests guide](https://docs.pact.io/consumer), our process is:

1. write some Unit tests using Pact
2. run the tests; Pact generates `test/pacts/…` files
3. run Acceptance tests using Cypress and the pact-stub-server

I'd like to keep Cypress, the pact-stub-server, and the unit-test suite all running in the background so I can develop continuously. As it is, I need to restart the Docker containers after every change.

### Possible Solutions

- `PactSource::Dir` could watch the directory rather than walk it during load.
- The pact-stub-server Dockerfile could use something like notify-rs to watch the directory and restart the server process on changes (after a debounce period)
